Add bitvector32
prysmaticlabs/go-bitfield pull request #45
Opened 2021-06-04 19:52 UTC by terencechain

Required for Altair sync committee `minimal` size

2021-06-04 20:43 UTC, prestonvanloon requested changes

2021-06-04 20:43 UTC, prestonvanloon commented on bitvector32.go
> +	byteArray := [8]byte{}
Why 8 byte array? Should it be 4 bytes?

2021-06-04 20:43 UTC, prestonvanloon commented on bitvector32.go
> +	byteArray := [8]byte{}
4 * 8 = 32

2021-06-04 20:45 UTC, prestonvanloon commented on bitvector32.go
> +}
Len returns the number of bits in the bitvector? That doesn't seem to match the implementation. Wouldn't it always be 32?

2021-06-04 21:26 UTC, terencechain commented
Please take another look @prestonvanloon

2021-06-05 18:44 UTC, prestonvanloon approved these changes
Looks good to me. We discussed offline that the .Bytes(), .BitIndices(), and .Count() methods do not behave appropriately when the underlying slice is improperly set to a slice larger than .Len()/8. I'll fix this in a follow up PR for all of the bitvector implementations

2021-06-05 18:52 UTC, merged